// Sample stock data for testing purposes
export const sampleStockItems = [
  {
    name: "Basmati Rice",
    category: "Grains",
    currentStock: 2.5,
    unit: "kg",
    minimumStock: 10,
    maximumStock: 50,
    costPerUnit: 80,
    supplier: "Rice Mills Co.",
    lastRestocked: "2024-01-10",
    expiryDate: "2024-06-15",
    description: "Premium quality basmati rice for biryani and pulao",
    location: "Storage Room A",
    batchNumber: "RM2024001"
  },
  {
    name: "Chicken (Fresh)",
    category: "Meat",
    currentStock: 5,
    unit: "kg",
    minimumStock: 15,
    maximumStock: 30,
    costPerUnit: 220,
    supplier: "Fresh Meat Ltd.",
    lastRestocked: "2024-01-12",
    expiryDate: "2024-01-18",
    description: "Fresh chicken for curries and biryani",
    location: "Refrigerator 1",
    batchNumber: "FM2024012"
  },
  {
    name: "Paneer",
    category: "Dairy",
    currentStock: 3,
    unit: "kg",
    minimumStock: 8,
    maximumStock: 20,
    costPerUnit: 300,
    supplier: "Dairy Fresh",
    lastRestocked: "2024-01-14",
    expiryDate: "2024-01-20",
    description: "Fresh cottage cheese for various dishes",
    location: "Refrigerator 2",
    batchNumber: "DF2024014"
  },
  {
    name: "Onions",
    category: "Vegetables",
    currentStock: 8,
    unit: "kg",
    minimumStock: 20,
    maximumStock: 100,
    costPerUnit: 25,
    supplier: "Veggie Mart",
    lastRestocked: "2024-01-11",
    expiryDate: "2024-02-15",
    description: "Fresh red onions for cooking",
    location: "Storage Room B",
    batchNumber: "VM2024011"
  },
  {
    name: "Cooking Oil",
    category: "Oils",
    currentStock: 15,
    unit: "liters",
    minimumStock: 25,
    maximumStock: 100,
    costPerUnit: 120,
    supplier: "Oil Industries",
    lastRestocked: "2024-01-08",
    expiryDate: "2024-12-31",
    description: "Refined sunflower oil for cooking",
    location: "Storage Room A",
    batchNumber: "OI2024008"
  },
  {
    name: "Tomatoes",
    category: "Vegetables",
    currentStock: 12,
    unit: "kg",
    minimumStock: 15,
    maximumStock: 50,
    costPerUnit: 40,
    supplier: "Veggie Mart",
    lastRestocked: "2024-01-13",
    expiryDate: "2024-01-25",
    description: "Fresh tomatoes for curries and salads",
    location: "Storage Room B",
    batchNumber: "VM2024013"
  },
  {
    name: "Wheat Flour",
    category: "Grains",
    currentStock: 25,
    unit: "kg",
    minimumStock: 30,
    maximumStock: 100,
    costPerUnit: 35,
    supplier: "Flour Mills",
    lastRestocked: "2024-01-09",
    expiryDate: "2024-07-09",
    description: "Whole wheat flour for rotis and naan",
    location: "Storage Room A",
    batchNumber: "FM2024009"
  },
  {
    name: "Milk",
    category: "Dairy",
    currentStock: 0,
    unit: "liters",
    minimumStock: 20,
    maximumStock: 50,
    costPerUnit: 55,
    supplier: "Dairy Fresh",
    lastRestocked: "2024-01-12",
    expiryDate: "2024-01-17",
    description: "Fresh full cream milk",
    location: "Refrigerator 1",
    batchNumber: "DF2024012"
  },
  {
    name: "Potatoes",
    category: "Vegetables",
    currentStock: 18,
    unit: "kg",
    minimumStock: 25,
    maximumStock: 80,
    costPerUnit: 20,
    supplier: "Veggie Mart",
    lastRestocked: "2024-01-10",
    expiryDate: "2024-03-10",
    description: "Fresh potatoes for various dishes",
    location: "Storage Room B",
    batchNumber: "VM2024010"
  },
  {
    name: "Spice Mix",
    category: "Spices",
    currentStock: 2,
    unit: "kg",
    minimumStock: 5,
    maximumStock: 20,
    costPerUnit: 400,
    supplier: "Spice House",
    lastRestocked: "2024-01-05",
    expiryDate: "2024-12-31",
    description: "Mixed spices for Indian cuisine",
    location: "Spice Rack",
    batchNumber: "SH2024005"
  }
];

// Function to load sample data
export const loadSampleStockData = () => {
  return sampleStockItems;
};